<?php

namespace IT\SearchBundle\Entity\Repository;

/**
 * SearchIndexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchIndexRepository extends \Doctrine\ORM\EntityRepository
{

    public function searchQB($terms)
    {

        $terms = strip_tags(strtolower($terms));

        $qb = $this->createQueryBuilder('si')
            ->select('si, MATCH_AGAINST(si.content, :textFilter \'IN NATURAL LANGUAGE MODE\') as score')
            ->where("MATCH_AGAINST(si.content, :textFilter 'IN NATURAL LANGUAGE MODE') >= 0.8")
            ->setParameter('textFilter', $terms)

            ->addOrderBy('score', 'DESC')
        ;

        return $qb;
    }

    public function searchExpandedQB($terms)
    {

        $terms = strip_tags(strtolower($terms));

        $qb = $this->createQueryBuilder('si')
            ->select('si, MATCH_AGAINST(si.content, :textFilter \'IN NATURAL LANGUAGE MODE WITH QUERY EXPANSION\') as score')
            ->where("MATCH_AGAINST(si.content, :textFilter 'IN NATURAL LANGUAGE MODE WITH QUERY EXPANSION') >= 0.8")
            ->setParameter('textFilter', $terms)

            ->addOrderBy('score', 'DESC')
        ;

        return $qb;
    }


}
