services:
  it_search.database.indexer:
    class: IT\SearchBundle\Services\DatabaseIndexer
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@event_dispatcher"
      - "%search.index.configuration%"

  it_search.database.searcher:
    class: IT\SearchBundle\Services\DatabaseSearcher
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@knp_paginator"
      - "%search.index.min_score%"
      - "%search.index.use_result_cache%"

  it_search.event_subscriber:
    class: IT\SearchBundle\EventListener\SearchEventSubscriber
    arguments:
      - "%search.index.enable_event_listener%"
      - "%search.index.configuration%"
      - "@service_container"
    tags:
      - { name: "doctrine.event_subscriber" }